# Generated by Django 4.2 on 2023-05-26 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lesTourApp", "0002_clientes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Areas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "id_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesTourApp.areas",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hoteles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("ciudad", models.CharField(max_length=200)),
                ("barrio", models.CharField(max_length=200)),
                ("direccion", models.CharField(max_length=100)),
                ("telefono", models.IntegerField()),
                ("email", models.CharField(max_length=100)),
                ("pisos", models.IntegerField()),
                ("habitaciones", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tipo_Habitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("capacidad", models.IntegerField()),
                ("costo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Puesto_Trabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "id_cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesTourApp.cargo",
                    ),
                ),
                (
                    "id_empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesTourApp.empleados",
                    ),
                ),
            ],
        ),
    ]
