# Generated by Django 4.2.1 on 2023-07-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesTourApp', '0006_reserva_huesped'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='empleados',
            options={'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='habitacion',
            options={'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='hoteles',
            options={'verbose_name_plural': 'Hoteles'},
        ),
        migrations.AlterModelOptions(
            name='puesto_trabajo',
            options={'verbose_name_plural': 'Puesto_Trabajo'},
        ),
        migrations.AlterModelOptions(
            name='reserva_huesped',
            options={'verbose_name_plural': 'Reserva_Huespedes'},
        ),
        migrations.AlterModelOptions(
            name='reservas',
            options={'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='tipo_habitacion',
            options={'verbose_name_plural': 'Tipo_Habitaciones'},
        ),
    ]
