# Generated by Django 3.2.12 on 2023-07-12 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesTourApp', '0008_ciudades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lesTourApp.ciudades'),
            preserve_default=False,
        ),
    ]
