# Generated by Django 4.2 on 2023-07-14 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lesTourApp", "0009_empleados_ciudad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="puesto_trabajo",
            name="id_cargo",
        ),
        migrations.RemoveField(
            model_name="puesto_trabajo",
            name="id_empleado",
        ),
        migrations.DeleteModel(
            name="Empleados",
        ),
        migrations.DeleteModel(
            name="Puesto_Trabajo",
        ),
    ]
