# Generated by Django 4.2 on 2023-07-14 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lesTourApp", "0010_remove_puesto_trabajo_id_cargo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ci_numero", models.IntegerField()),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=100)),
                ("telefono", models.IntegerField()),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesTourApp.cargo",
                    ),
                ),
                (
                    "ciudad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesTourApp.ciudades",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesTourApp.hoteles",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Empleados",
            },
        ),
    ]
